# This workflow will install Python dependencies, run tests, lint, and perform SonarCloud analysis
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        # python -m unittest discover -v -s src -p 'test_*.py'
        coverage run -m unittest discover -v -s src -p 'test_*.py'
        coverage report -m --fail-under=80  # Ajusta el umbral según tus necesidades

  # sonarcloud:
  #   runs-on: ubuntu-latest
  #   needs: build  # Este trabajo depende del éxito del trabajo 'build'

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.10'

  #   - name: Download and install SonarScanner
  #     run: |
  #         mkdir -p ~/sonar-scanner
  #         curl -L -o ~/sonar-scanner/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
  #         unzip -o ~/sonar-scanner/sonar-scanner.zip -d ~/sonar-scanner
  #         export PATH=$PATH:~/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin
  #         echo "PATH: $PATH"
  
  #   - name: SonarCloud Scan
  #     run: |
  #         ~/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
  #         -Dsonar.projectKey=ssanga_df-filtering \
  #         -Dsonar.organization=ssanga \
  #         -Dsonar.sources=src \
  #         -Dsonar.tests=tests \
  #         -Dsonar.host.url=https://sonarcloud.io \
  #         -Dsonar.login=$SONAR_TOKEN  # Set your SonarCloud token as a secret in your GitHub repository
  #         -Dsonar.python.coverage.reportPaths=coverage.xml
